export const Icons = {
  hourglass: '⌛',
  gear: '⚙',
  home: '🏠',
  save: '💾',
  close: '✕',
  back: '←',
  edit: '✎',
  trash: '🗑',
  play: '▶',
  stop: '■',
  thinking: '💭',
  memory: '🧠',
  world: '🌍',
  character: '👤',
  settings: '⚙',
  theme: '🎨',
  api: '🔌',
  storage: '📦',
  newGame: '🆕',
  continue: '▶',
  export: '📤',
  import: '📥',
} as const;
